aerogearcatalog/keycloak-apb

Makefile
README.md

**What**
Updating references to org for docker relevant items.
**Verification**
Docker info in README should have valid values rather than NaN

update docker org

---

README.md

**What**
update apb image
@david-martin @aidenkeating

update apb image

---

README.md
roles/bind-keycloak-apb/tasks/main.yml
roles/bind-keycloak-apb/templates/bind.json.j2
roles/provision-keycloak-apb/tasks/provision-keycloak.yml
roles/unbind-keycloak-apb/tasks/main.yml

fix for #10 
To verify:
* check out the code the build the apb locally
* provision a new Keycloak instance
* Try bind the keycloak instance to a sync service, make sure a secret is created
* Try unbind. The secret should be deleted.
ping @aidenkeating @maleck13 @philbrookes for review

 🐛 fix a few issues in the bind/unbind playbooks

---

README.md
apb_overview.md

ping @maleck13 @aidenkeating @matzew

 📝 add an overview doc for the keycloak apb

---

Jenkinsfile

based on https://github.com/aerogearcatalog/metrics-apb/pull/16

More unique name for the OpenShift project name

---

roles/provision-keycloak-apb/tasks/label-serviceinstance.yml
roles/provision-keycloak-apb/tasks/main.yml
roles/provision-keycloak-apb/tasks/provision-keycloak.yml

broke this out into its own task to make sure it is done first
@matzew @pb82

add a task for setting serviceinstance label

---

README.md

Same motivation as in https://github.com/aerogearcatalog/metrics-apb/pull/21

Updated readme - testing

---

apb.yml

**Description** 
Update `apb.yml` to include options for shared services. See Phil's proposal [here](https://github.com/aerogear/proposals/blob/master/apbs/use-shared-services-across-namespaces.md).

AEROGEAR-1992 Add options for shared services

---

roles/provision-keycloak-apb/tasks/provision-keycloak.yml

https://issues.jboss.org/browse/AEROGEAR-2178

Fixed getting the keycloak pod name

---

roles/deprovision-keycloak-apb/tasks/deprovision-keycloak.yml
roles/provision-keycloak-apb/tasks/provision-keycloak.yml
roles/provision-keycloak-apb/tasks/provision-postgres-ephemeral.yml
roles/provision-keycloak-apb/tasks/provision-postgres.yml

See [AEROGEAR-2012](https://issues.jboss.org/browse/AEROGEAR-2012)

usage of k8s deployment

---

Makefile

Move minishift rule from default spot.

move minishift rule from default

---

roles/provision-keycloak-apb/tasks/configure-keycloak.yml
roles/provision-keycloak-apb/templates/configmap.yml.j2

Config map should now look like this:

Remove creation of bearer client on provision

---

roles/bind-keycloak-apb/tasks/main.yml

ensure the url is the full auth url required by the sdk

set the full auth url on bind

---

roles/bind-keycloak-apb/tasks/main.yml

replace missing config fields in keycloak binding data

replace missing config fields in keycloak binding data

---

roles/bind-keycloak-apb/tasks/main.yml
roles/unbind-keycloak-apb/tasks/main.yml

**Description**
Annotate the mobile client in the bind playbook to link to the Keycloak public client

Add public client annotation

---

roles/bind-keycloak-apb/tasks/main.yml

see https://groups.google.com/forum/#!topic/aerogear/IQukeGKOcXI

/s/Keycloak/keycloak

---

Jenkinsfile

Same approach as in https://github.com/aerogearcatalog/metrics-apb/pull/64/files

Test on ci-rhos ocp slave

---

Dockerfile
roles/provision-keycloak-apb/files/standalone-ha.xml
roles/provision-keycloak-apb/tasks/provision-keycloak.yml

https://issues.jboss.org/browse/AEROGEAR-3500

exported standalone-ha.xml to configmap

---

Jenkinsfile
playbooks/provision.yml
playbooks/test.yml
roles/bind-keycloak-apb/tasks/main.yml
roles/provision-keycloak-apb/tasks/main.yml
roles/provision-keycloak-apb/tasks/provision-keycloak.yml
roles/unbind-keycloak-apb/tasks/main.yml

Correcting issue found by @wei-lee: https://github.com/aerogearcatalog/keycloak-apb/issues/113
Also corrected similar issue in unbind.

fix missing tag in bind

---

roles/bind-keycloak-apb/tasks/main.yml
roles/deprovision-keycloak-apb/tasks/cleanup-resources.yml
roles/provision-keycloak-apb/defaults/main.yml
roles/provision-keycloak-apb/tasks/main.yml
roles/provision-keycloak-apb/tasks/provision-keycloak.yml
roles/test-keycloak-apb/tasks/bind.yml
roles/test-keycloak-apb/tasks/deprovision.yml
roles/test-keycloak-apb/tasks/provision.yml
roles/test-keycloak-apb/tasks/unbind.yml
roles/unbind-keycloak-apb/tasks/main.yml
vars/main.yml

https://issues.jboss.org/browse/AEROGEAR-8317
If metrics-apb is not provisioned yet in the project, save keycloak dashboard to configmap so metrics-apb could grab that and apply it later.

feat: save keycloak dashboard to confimap

---

roles/provision-keycloak-apb/tasks/provision-postgres.yml
vars/main.yml

See: [AEROGEAR-8778](https://issues.jboss.org/browse/AEROGEAR-8778)

Add recreate strategy to postgres
