roles/deprovision-keycloak-apb/tasks/main.yml
Currently we only delete the Keycloak resources that are created
during provisioning. However, postgres and keycloak metrics are
also created and each contain a number of different resources
(services, deployments, secrets etc.). This cleans up every
resource that is created during the Keycloak APB provisioning.
=> Remove all created resources in deprovision

roles/provision-keycloak-apb/tasks/provision-keycloak.yml
Currently we do not wait enought time for the jar to be copied over, this change extends the time.
=> Extend copy jar retries

roles/bind-keycloak-apb/tasks/main.yml
Currently the bind playbook isn't re-runnable. This is due to a conflict with the current state while creating the service. 
The conflict returns a 409 which in turn forces and exit of the playbook. To over come this, we allow a 409 status code along with a created status code of 201. This allows the playbook to continue without throwing an error and forcing an exit of the playbook.
@aidenkeating
=> Bind Playbook Fix

roles/provision-keycloak-apb/tasks/provision-keycloak.yml
Currently the Keycloak metrics are not discoverable by Prometheus. This is because the Keycloak service does not contain the org.aerogear.metrics/plain_endpoint annotation pointing at the Keycloak metrics endpoint.
The annotation was added so that when Prometheus is provisioned the Keycloak metrics are discoverable.
=> Added annotation for Prometheus

roles/provision-keycloak-apb/templates/secret.yml.j2
Currently if a password of '123' is provided it will cause the JSON
parsing in the provision role to fail when creating the keycloak
public config and persisting it.
This change wraps the username and password variables in quotes to
ensure that these fields are treated as strings.
=> Fix limitations with username and password

roles/deprovision-keycloak-apb/tasks/main.yml, roles/provision-keycloak-apb/tasks/provision-keycloak.yml, roles/provision-keycloak-apb/templates/configmap.yml.j2
Split up the keycloak config into secret and non secret parts where the non-secret parts are stored in a config map.
Based on this proposal: https://github.com/aerogear/proposals/blob/master/apbs/create-secret-and-configmap-during-provision.md#proposed-solution
To verify, checkout this branch and provision the apb. After everything is deployed, check that both, a config map and a secret with the name `keycloak` exist. The secret should only contain username and password. Delete the service instance. The config map and the secret should also be deleted.
=> AEROGEAR-1986 split up keycloak config into secret and non secret parts

roles/provision-keycloak-apb/files/keycloak-dashboard.json
* Removes conflicting and unnecessary `id` property from.
* `0` instead of `N/A` for counters where no data.
* Error type in *Login Errors*'s leyend instead of provider.
* Prevent charts from displaying gaps when there is null data. Display a connecting line instead.
=> Adds small corrections to Keycloak dashboard that are missing from PR

playbooks/vars/test_defaults.yml, roles/provision-keycloak-apb/tasks/main.yml, roles/provision-keycloak-apb/tasks/provision-postgres-ephemeral.yml
https://issues.jboss.org/browse/AEROGEAR-1987
I've added ephemeral version of PostgreSQL (just excluded PV configuration and volume mounting) to temporarily resolve the issue with failing builds.
=> Provision role for test with ephemeral PostgreSQL

roles/provision-keycloak-apb/tasks/provision-keycloak.yml
@rachael-oregan Would you mind taking a quick look? Based on this comment, https://issues.jboss.org/browse/KEYCLOAK-3765?focusedCommentId=13312743&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13312743
Have tested with the Auth example app
=> Use public access type instead of confidential for client apps

roles/test-provision-apb/tasks/main.yml
I've noticed a strange behaviour of the "check for metrics endpoint" in [latest builds](https://jenkins-wendy.ci.feedhenry.org/job/AeroGearCatalog/job/keycloak-apb/job/master/26/console)
Apparently the metric `kc_logged_in_users` is no longer present in keycloak's metric endpoint.
=> Fixed test of metrics endpoint

roles/provision-keycloak-apb/tasks/label-serviceinstance.yml
This pr adds a generic label to allow the UI to find all serviceinstances created by mobile apbs
=> add generic mobile enabled label

roles/unbind-keycloak-apb/tasks/main.yml
On unbind, it should connect to the remote keycloak server. It should remove the client bearer from the realm and the resource should be deleted in the local namespace.
This PR is dependent on the changes from https://github.com/aerogearcatalog/keycloak-apb/pull/49
Related JIRA - https://issues.jboss.org/browse/AEROGEAR-1996
- Ensure that the client bearer is deleted from the Keycloak realm it was created in.
- Ensure that the resource from the local namespace is removed.
- Ensure that you can create another client bearer with the same name within the same Keycloak realm once removed.
=> [AEROGEAR-1996] Update unbind playbook to deconfigure when shared

roles/bind-keycloak-apb/tasks/main.yml, roles/provision-keycloak-apb/tasks/addrealmuser-keycloak.yml, roles/unbind-keycloak-apb/tasks/main.yml
When creating a binding with the Keycloak Service, the bind fails due to `IS_SHARED` field not available in the asb provision credentials. The `KEYCLOAK_REALM` used when registering the value for `KCADM_REALM` is also not found. It's declaration needs to be in a separate `set_fact` task from the declaration of the `KEYCLOAK_REALM` variable.
When deleting the binding, the unbind process fails due to the `KEYCLOAK_REALM` variable, used by the `KCADM_REALM`, is not found. This also needs to be in a separate `set_fact` task from the declaration of the `KEYCLOAK_REALM` variable.
**Errors**
Bind Process: 
> FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'IS_SHARED'...}
> FAILED! => {"msg": "The task includes an option …
=> Fix undefined variables bind and unbind errors

roles/deprovision-keycloak-apb/tasks/cleanup-keycloak.yml
Add a check if the public/bearer client created during provision exists first before attempting to delete. A check for the user created during provision is also added to see if it exists before attempting to delete.
**Test Cases**
- Ensure that the Keycloak service can be deleted successfully even when the clients/realm has already been removed.
- Ensure that when 401 and 403 errors are received, it displays a proper error message in the logs.
=> Check if client exists before deleting

Makefile, README.md
Don't force the use of the containerised apb tools in Makefile commands, apb should be installed locally using one of the recommended approaches https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/apb_cli.md#installing-the-apb-tool
=> AEROGEAR-2491 - Don't force the use of the containerised apb tools in Makefile command.

roles/unbind-keycloak-apb/tasks/main.yml
The unbind process fails due to `keycloak_realm` being undefined when used to set the `kcadm_realm`.  These needs to be separated into two different set fact tasks to ensure that the `keycloak_realm` var is defined before it is used in setting the `kcadm_realm` var.
```
TASK [unbind-keycloak-apb : set_fact] ******************************************
--
  | fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'KEYCLOAK_REALM' is undefined\n\nThe error appears to have been in '/opt/ansible/roles/unbind-keycloak-apb/tasks/main.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
```
This is related to this JIRA Ticket - …
=> [FIX] Ensure that keycloak realm var is defined during unbind

Dockerfile, roles/bind-keycloak-apb/tasks/main.yml, vars/main.yml
**Description** 
Updates the bind playbook with a new format for annotating the mobile client: 
```yaml
org.aerogear.binding.<service-instance-name>/<key>: <value>
``` 
The value is a JSON string with the structure:
```json
{"label": "<display-name>", "type": "[string|href]", "value": "<value>"}
```
e.g.
```yaml
org.aerogear.binding.localregistry-keycloak-apb-7zqk9/realm: '{label: "Keycloak Realm", value: "test", type: "string"}'
org.aerogear.binding.localregistry-keycloak-apb-7zqk9/uri: >-
{label: "Keycloak URL", value:
"https://keycloak-test.192.168.42.52.nip.io", type: "href"}
```
**Note**
The `--overwrite` flag is set to true, so new annotations with the same name will be overwritten
=> Update bind annotation format

roles/bind-keycloak-apb/tasks/main.yml
**Description**
Update `name` field in config to be consistent with other apbs (service name instead of service instance name)
=> Update name field in keycloak config

roles/provision-keycloak-apb/tasks/provision-keycloak.yml, roles/provision-keycloak-apb/tasks/provision-postgres.yml, vars/test.yml
Fixes the issue of having a single application (and a single route) for multiple keycloak instances.
(Dockerfile is added because it was out of date)
=> Update application labels to be unique

Dockerfile, playbooks/requirements.yml, roles/bind-keycloak-apb/tasks/main.yml, roles/oc-patch-file-to-configmap/Readme.md, roles/oc-patch-file-to-configmap/tasks/main.yml, roles/oc-patch-file-to-configmap/templates/oc-patch.json.j2, roles/provision-keycloak-apb/tasks/provision-keycloak.yml
=> 🔥 Remove the need for jq and ansible-galaxy install

Dockerfile.rhel7, apb.yml, roles/provision-keycloak-apb/defaults/main.yml, roles/provision-keycloak-apb/tasks/provision-keycloak.yml
This change also:
- Removes the dependencies section from the apb.yml (we've removed it from the other APBs, as it would be too easy to fall out-of-sync with what's _actually_ being used in the provision playbook.
- Adds a default variable for the `keycloak_image` value, to make it more like the postgres variables in the same file (and more like our other APBs) (and so that there isn't one file to update the image path, and another to update the tag).
=> 🐳 Add alternative Dockerfile for RHEL7 
